version: 2
jobs:
  ansible_lint:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Install ansible-lint
          command: pip install ansible-lint
      - run:
          name: Syntax check playbook
          command: ansible-playbook --syntax-check tests/test.yml
      - run:
          name: Show ansible-lint version
          command: ansible-lint --version
      - run:
          name: Retrieve Ansible lint rules file
          command: >
            cd /tmp

            git clone
            https://github.com/TomonoriMatsumura/ansible_joke-programs_lint-rules
      - run:
          name: Execute ansible-lint
          command: >
            find . -type f -name '*.yml' | xargs ansible-lint -c /tmp/ansible_joke-programs_lint-rules/.ansible-lint-rules

workflows:
  version: 2
  lint_and_test:
    jobs:
      - ansible_lint
